Circuit breaker implementation
Postcon/resilience pull request #1
Opened 2019-10-01 04:24 UTC by DrSchimke

2019-10-01 05:44 UTC, arosslau approved these changes
👍

2019-10-31 07:58 UTC, dreadwarrior requested changes

2019-10-31 07:58 UTC, dreadwarrior commented on README.md
> +[![Build Status](https://secure.travis-ci.org/DrSchimke/resilience.png)](http://travis-ci.org/DrSchimke/resilience)
Hier sollte die Travis-CI URL zum Build von der Organisation "Postcon" enthalten sein. Können wir das selbst einrichten oder muss das Andy machen?

2019-10-31 07:58 UTC, dreadwarrior commented on lib/AbstractCircuitBreaker.php
> +<?php declare(strict_types=1);
Bitte `declare()` auf eine eigene Zeile packen, es könnte sonst leicht übersehen werden. Siehe auch https://github.com/FriendsOfPHP/PHP-CS-Fixer **blank_line_before_statement**.

2019-10-31 08:08 UTC, dreadwarrior approved these changes

2019-10-31 13:02 UTC, DrSchimke commented on README.md
> +[![Build Status](https://secure.travis-ci.org/DrSchimke/resilience.png)](http://travis-ci.org/DrSchimke/resilience)
Für den change in der Readme gibt es in meinem Repo bereits einen PR. Und in der https://github.com/Postcon/BehatShellExtension/edit/master/README.md ist bereits ein Postcon-Travis erwähnt. Das hatten wir also irgendwann schonmal eingerichtet.

2019-10-31 17:44 UTC, dreadwarrior commented on README.md
> +[![Build Status](https://secure.travis-ci.org/DrSchimke/resilience.png)](http://travis-ci.org/DrSchimke/resilience)
👍

2019-11-01 08:36 UTC, acrolyt requested changes

2019-11-01 08:36 UTC, acrolyt commented on lib/InMemoryCircuitBreaker.php
> +    private $lastErrorTs = 0;
suggestion: $lastErrorTimestamp

2019-11-01 08:36 UTC, acrolyt commented on tests/Integration/AbstractCircuitBreakerTest.php
> +    protected const NAME       = 'system to be circuit-breaked';
circuit-broken

2019-11-01 08:36 UTC, acrolyt commented on tests/Unit/AbstractCircuitBreakerTest.php
> +        $circuitBreaker->check();
acting after assertion?

2019-11-01 08:36 UTC, acrolyt commented on tests/Unit/AbstractCircuitBreakerTest.php
> +        $circuitBreaker->check();
acting after assertion?

2019-11-01 09:50 UTC, merged